services:
  - riak
language: elixir
elixir:
  - 1.6.6
  - 1.7.4
  - 1.8.0
before_script:
  - sudo riak-admin bucket-type create riak_ecto3_test_example '{"props":{"datatype":"map"}}'
  - sudo riak-admin bucket-type activate riak_ecto3_test_example
script:
  - MIX_ENV=test mix travis
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
