language: elixir
elixir:
  - 1.6.6
  - 1.7.4
  - 1.8.0
# Configure Riak properly:
before_install:
  - sudo sed -i 's/storage_backend = bitcask/storage_backend = leveldb/' /etc/riak/riak.conf
  - sudo sed -i 's/search = off/search = on/' /etc/riak/riak.conf
  - sudo service riak start
before_script:
  - sudo riak-admin bucket-type create riak_ecto3_test_example '{"props":{"datatype":"map"}}'
  - sudo riak-admin bucket-type activate riak_ecto3_test_example
  - mix riak_ecto3.create_search_index riak_ecto3_test_example localhost 8087
script:
  - MIX_ENV=test mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
